#!/bin/bash
# Small tests:
# Using perf to record and report - profile - CPU usage.
# (c) Kaiwan NB, kaiwanTECH
# License: MIT.
name=$(basename $0)

die()
{
echo >&2 "FATAL: $@"
exit 1
}
# runcmd
# Parameters
#   $1 ... : params are the command to run
runcmd()
{
	[ $# -eq 0 ] && return
	echo "$@"
	eval "$@"
}

SAMPLING_FREQ=99
TIME=10s

process_report()
{
  echo "
[+] Reporting ..."
  runcmd "perf report --sort cpu,comm --stdio"
  runcmd "perf script -i perf.data > profile_data.txt"
  chown ${LOGNAME}:${LOGNAME} profile_data.txt
# TIP: we've exported the trace to a file; u can try
}
trap process_report INT QUIT

test1_fork()
{
  echo "[+] test1_fork(): recording ... pl wait for time of ${TIME} ..."
  runcmd "perf record -F ${SAMPLING_FREQ} \
	-C 0 \
	--call-graph dwarf \
	-- taskset 01 stress-ng --malloc 1 \
	-t ${TIME}"
  # -C 0 : only on cpu #0
	#-- taskset 01 stress-ng --fork 1 \
	#-- taskset 01 stress-ng --io 1 \
}

test2_matrixmul_pthrd()
{
  local PRG=./thrd_matrixmul_dbg
  [[ ! -f ${PRG} ]] && die "Program \"${PRG}\" not found."

  echo "[+] test2_matrixmul_pthrd(): recording ... pl wait ..."
  runcmd "perf record -F ${SAMPLING_FREQ} \
	-a \
	--call-graph dwarf \
	-- ${PRG}"
  # -a : sample across all cpu cores
}

#--
# Src for this demo's here:
#  https://github.com/kaiwan/cpu_sched_demo
# Params
#  $1 : 0 = run the prg ver compiled without symbols
#       1 = run the prg ver compiled with symbols
test3_cpusched_mt_demo()
{
  local PRG=./sched_pthrd_rtprio_dbg
  local ARGS="32"

  echo -n "*** Running program "
  [[ $1 -eq 0 ]] && {
    PRG=./sched_pthrd_rtprio
    echo "WITHOUT symbols ***"
  } || {
    echo "WITH symbols ***"
  }
  [[ ! -f ${PRG} ]] && die "Program \"${PRG}\" not found."

  echo "[+] test3_cpusched_mt_demo(): recording ... pl wait ..."
  runcmd "perf record -F ${SAMPLING_FREQ} \
	-C 0 \
	--call-graph dwarf \
	-- taskset 01 ${PRG} ${ARGS}"
  # -C 0 : only on cpu #0
}

test4_fork_exit()
{
  local PRG=./fork_test_dbg
  [[ ! -f ${PRG} ]] && die "Program \"${PRG}\" not found."

  echo "[+] test4_fork_exit(): recording ... pl wait ..."
  runcmd "perf record -F ${SAMPLING_FREQ} \
	-C 1 \
	--call-graph dwarf \
	-- taskset 02 ${PRG}"
  # -a : sample across all cpu cores
}

menu()
{
echo "--------------- MENU --------------------

Select a test case to run under perf:

1. fork (via stress-ng)
2. matrixmul pthread app
3. CPU sched pthread demo app : without symbols
4. CPU sched pthread demo app : with symbols
5. fork-exit in loop app
"
read choice
case ${choice} in
  1) test1_fork
     ;;
  2) test2_matrixmul_pthrd
     ;;
  3) test3_cpusched_mt_demo 0  # without symbols
     ;;
  4) test3_cpusched_mt_demo 1  # with symbols (in the app only)
     ;;
  5) test4_fork_exit
     ;;
  *) echo "Invalid choice" ; exit 1
esac
}


#--- 'main' ---
[[ $(id -u) -ne 0 ]] && die "${name}: need root."
which stress-ng >/dev/null || die "pl install the stress-ng package"
menu
process_report
exit 0
